AUGMENTATION: True

IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16

INCLUDE_TOP: False

EPOCHS: 2
# EPOCHS: 50

CLASSES: 8
WEIGHTS: imagenet

FREEZE_LAYERS_TILL: 100
# FREEZE_LAYERS_TILL: 0

# LEARNING_RATE: 0.01
LEARNING_RATE: 0.001