artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 
  local_data_file: 'artifacts/data_ingestion/Facial Expressions Dataset.zip'
  unzip_dir: artifacts/data_ingestion